// src/lib/components/Scene3D.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import * as THREE from 'three';
  import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

  let container: HTMLDivElement;
  let isLight = $state(false);

  onMount(() => {
    isLight = document.documentElement.classList.contains('light');
    const handler = () => {
      isLight = document.documentElement.classList.contains('light');
      if (isLight) {
        for (let i = 0; i < PARTICLE_COUNT; i++) {
          instanced.setColorAt(i, new THREE.Color(LIGHT_COLORS[Math.floor(Math.random() * 5)]));
        }
        const count = geo.attributes.position.count;
        const colors = new Float32Array(count * 3);
        for (let i = 0; i < count; i++) {
          const c = LIGHT_COLORS[Math.floor(Math.random() * 5)];
          colors[i * 3] = ((c >> 16) & 255) / 255;
          colors[i * 3 + 1] = ((c >> 8) & 255) / 255;
          colors[i * 3 + 2] = (c & 255) / 255;
        }
        geo.setAttribute('color', new THREE.BufferAttribute(colors, 3));
        mat.vertexColors = true;
        mat.color.setHex(0xffffff);
      } else {
        for (let i = 0; i < PARTICLE_COUNT; i++) {
          instanced.setColorAt(i, new THREE.Color(0x0070f3));
        }
        geo.deleteAttribute('color');
        mat.vertexColors = false;
        mat.color.setHex(0x0070f3);
      }
      if (instanced.instanceColor) instanced.instanceColor.needsUpdate = true;
    };
    window.addEventListener('themechange', handler);

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(50, 1, 0.1, 1000);
    camera.position.z = 5;

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5));
    renderer.setSize(container.clientWidth, container.clientHeight);
    renderer.setClearColor(0x000000, 0);
    container.appendChild(renderer.domElement);

    const ambientLight = new THREE.AmbientLight(0xffffff, 0.2);
    scene.add(ambientLight);
    const dirLight = new THREE.DirectionalLight(0xffffff, 0.8);
    dirLight.position.set(5, 5, 5);
    scene.add(dirLight);

    const LIGHT_COLORS = [0xde3b84, 0xffc12d, 0xf7a361, 0xee847b, 0xd6007d];
    const geo = new THREE.IcosahedronGeometry(1.4, 1);
    const mat = new THREE.MeshStandardMaterial({
      color: 0x0070f3,
      metalness: 0.9,
      roughness: 0.15,
      wireframe: true
    });
    const mesh = new THREE.Mesh(geo, mat);
    scene.add(mesh);

    const PARTICLE_COUNT = 100;
    const particleGeo = new THREE.SphereGeometry(1, 6, 6);
    const particleMat = new THREE.MeshBasicMaterial({
      color: 0xffffff,
      transparent: true,
      opacity: 0.6
    });
    const instanced = new THREE.InstancedMesh(particleGeo, particleMat, PARTICLE_COUNT);
    const dummy = new THREE.Object3D();
    const basePos = new Float32Array(PARTICLE_COUNT * 3);
    const curPos = new Float32Array(PARTICLE_COUNT * 3);
    const vel = new Float32Array(PARTICLE_COUNT * 3);
    for (let i = 0; i < PARTICLE_COUNT; i++) {
      basePos[i * 3] = (Math.random() - 0.5) * 15;
      basePos[i * 3 + 1] = (Math.random() - 0.5) * 15;
      basePos[i * 3 + 2] = (Math.random() - 0.5) * 15;
      curPos[i * 3] = basePos[i * 3];
      curPos[i * 3 + 1] = basePos[i * 3 + 1];
      curPos[i * 3 + 2] = basePos[i * 3 + 2];
      vel[i * 3] = (Math.random() - 0.5) * 0.005;
      vel[i * 3 + 1] = (Math.random() - 0.5) * 0.005;
      vel[i * 3 + 2] = (Math.random() - 0.5) * 0.005;
    }
    scene.add(instanced);
    for (let i = 0; i < PARTICLE_COUNT; i++) {
      instanced.setColorAt(i, new THREE.Color(isLight ? LIGHT_COLORS[Math.floor(Math.random() * 5)] : 0x0070f3));
    }
    instanced.instanceColor!.needsUpdate = true;

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.enableZoom = false;
    controls.enablePan = false;
    controls.autoRotate = true;
    controls.autoRotateSpeed = 0.4;

    const pointer = { x: 0, y: 0 };
    container.addEventListener('pointermove', (e) => {
      const r = container.getBoundingClientRect();
      pointer.x = ((e.clientX - r.left) / r.width) * 2 - 1;
      pointer.y = -((e.clientY - r.top) / r.height) * 2 + 1;
    });

    const resize = () => {
      const w = container.clientWidth;
      const h = container.clientHeight;
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
      renderer.setSize(w, h);
    };
    window.addEventListener('resize', resize);

    let raf = 0;
    const animate = () => {
      raf = requestAnimationFrame(animate);
      const dt = 0.016;
      mesh.rotation.y += dt * 0.3;

      for (let i = 0; i < PARTICLE_COUNT; i++) {
        const i3 = i * 3;
        curPos[i3] += (basePos[i3] + pointer.x * 5 * 0.3 - curPos[i3]) * 0.02;
        curPos[i3 + 1] += (basePos[i3 + 1] + pointer.y * 5 * 0.3 - curPos[i3 + 1]) * 0.02;
        curPos[i3] += vel[i3];
        curPos[i3 + 1] += vel[i3 + 1];
        curPos[i3 + 2] += vel[i3 + 2];
        dummy.position.set(curPos[i3], curPos[i3 + 1], curPos[i3 + 2]);
        dummy.scale.setScalar(0.015 + Math.random() * 0.01);
        dummy.updateMatrix();
        instanced.setMatrixAt(i, dummy.matrix);
      }
      instanced.instanceMatrix.needsUpdate = true;
      controls.update();
      renderer.render(scene, camera);
    };
    animate();

    return () => {
      window.removeEventListener('themechange', handler);
      window.removeEventListener('resize', resize);
      cancelAnimationFrame(raf);
      renderer.dispose();
      container.removeChild(renderer.domElement);
    };
  });
</script>

<div bind:this={container} class="absolute inset-0 w-full h-full"></div>

// src/components/Scene3D.tsx
/**
 * Scene3D.tsx
 * Three.js canvas with DRACO-ready model loading, particles, and orbit controls.
 * Uses dpr={[1,2]} to limit pixel density on retina/mobile.
 *
 * HOW TO LOAD A DRACO-COMPRESSED .glb:
 *   import { useGLTF } from "@react-three/drei";
 *   // At module scope, set the DRACO decoder path:
 *   useGLTF.preload("/models/your-model.glb");
 *   // Inside your component:
 *   const { scene } = useGLTF("/models/your-model.glb", true,
 *     undefined,
 *     (loader) => {
 *       const dracoLoader = new DRACOLoader();
 *       dracoLoader.setDecoderPath("https://www.gstatic.com/draco/versioned/decoders/1.5.6/");
 *       loader.setDRACOLoader(dracoLoader);
 *     }
 *   );
 */
import { Suspense, useRef, useState, useEffect } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import * as THREE from "three";
import Particles from "./Particles";

const LIGHT_BRAND_COLORS = [
    new THREE.Color("#DE3B84"),
    new THREE.Color("#FFC12D"),
    new THREE.Color("#F7A361"),
    new THREE.Color("#EE847B"),
    new THREE.Color("#D6007D"),
];

function CentralModel({ isLight }: { isLight: boolean }) {
    const meshRef = useRef<THREE.Mesh>(null);
    const geoRef = useRef<THREE.IcosahedronGeometry>(null);
    const matRef = useRef<THREE.MeshStandardMaterial>(null);

    // Imperatively update geometry colors and material when theme changes
    useEffect(() => {
        const geo = geoRef.current;
        const mat = matRef.current;
        if (!geo || !mat) return;

        if (isLight) {
            const count = geo.attributes.position.count;
            const colors = new Float32Array(count * 3);
            for (let i = 0; i < count; i++) {
                const c = LIGHT_BRAND_COLORS[Math.floor(Math.random() * LIGHT_BRAND_COLORS.length)];
                colors[i * 3]     = c.r;
                colors[i * 3 + 1] = c.g;
                colors[i * 3 + 2] = c.b;
            }
            geo.setAttribute("color", new THREE.BufferAttribute(colors, 3));
            mat.vertexColors = true;
            mat.color.set("#ffffff");
        } else {
            if (geo.hasAttribute("color")) geo.deleteAttribute("color");
            mat.vertexColors = false;
            mat.color.set("#0070f3");
        }
        mat.needsUpdate = true;
    }, [isLight]);

    // Slow auto-rotation (360° in ~20 seconds)
    useFrame((_, delta) => {
        if (meshRef.current) {
            meshRef.current.rotation.y += delta * 0.3;
        }
    });

    return (
        <mesh ref={meshRef} position={[0, 0, 0]}>
            <icosahedronGeometry ref={geoRef} args={[1.4, 1]} />
            <meshStandardMaterial
                ref={matRef}
                color="#0070f3"
                metalness={0.9}
                roughness={0.15}
                wireframe
            />
        </mesh>
    );
}

export default function Scene3D() {
    const [isLight, setIsLight] = useState(false);

    useEffect(() => {
        setIsLight(document.documentElement.classList.contains("light"));
        const handler = (e: Event) => {
            const detail = (e as CustomEvent).detail;
            setIsLight(!detail.isDark);
        };
        window.addEventListener("themechange", handler);
        return () => window.removeEventListener("themechange", handler);
    }, []);

    return (
        <Canvas
            dpr={[1, 1.5]}
            camera={{ position: [0, 0, 5], fov: 50 }}
            style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                height: "100%",
                background: "transparent",
            }}
        >
            <Suspense fallback={null}>
                <ambientLight intensity={0.2} />
                <directionalLight position={[5, 5, 5]} intensity={0.8} />

                {/* Central model with auto-rotation */}
                <CentralModel isLight={isLight} />

                {/* 600 InstancedMesh particles as background */}
                <Particles isLight={isLight} />

                {/* Orbit controls: drag to rotate, scroll zoom DISABLED */}
                <OrbitControls
                    enableZoom={false}
                    enablePan={false}
                    autoRotate
                    autoRotateSpeed={0.4}
                />
            </Suspense>
        </Canvas>
    );
}
